### ISSUE TITLE
Not displaying

### ISSUE THREAD

**Issue by dimijazz** [Mint-System/Odoo-Development#9]
I used your module 
 https://github.com/Mint-System/Odoo-Apps-Product-Attribute/tree/14.0/product_country_of_origin
and this field is not displaying .
Any idea what I do wrong? I also tried to add it in the template itself.
<span t-field="o.product_id.x_country_of_origin.code"/>
Thank you in advance
Dimi

**Comment by janikvonrotz** [comment]
> @dimijazz Here is an example: https://odoo.build/snippets.html#product-hs-code-and-origin
